// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "animate.css"; //
import Nav from "@/layout/nav";
import Footer from "@/layout/footer";
import Logo from '@/NavBar/Logo'


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <Logo />
      <Nav />
        {children}
      <Footer />
      </body>
    </html>
  );
}
